### ISSUE TITLE
circular dep in node modules 12GB

### ISSUE THREAD

**Issue by hrgdavor** [jsxcad/JSxCAD#1122]
I was curious about the project and pulled it form git
npm install creaed a huge folder

![image](https://user-images.githubusercontent.com/2480762/159791911-1c18887d-61f8-447e-b3bd-2a06d1958eed.png)

**Comment by BarbourSmith** [comment]
Interesting, I just grabbed a fresh copy and built it and I'm not seeing that. This is after running `npm install` and then `npm run bootstrap`?

<img width="539" alt="image" src="https://user-images.githubusercontent.com/9359447/159831125-b2796589-942c-4e30-b42f-61dbeffc6054.png">

Conveniently if you just want to check out the project there is a hosted version [here](https://jsxcad.js.org/alpha/) that you can try. Not sure I'm supposed to be telling people that since it's alpha.

There's some documentation [here](https://github.com/jsxcad/JSxCAD/blob/master/nb/documentation/index.md) for the language itself, but the UI isn't in there yet...something useful to know is that `shift+enter` will recompute the notebook for you.

**Comment by pentacular** [comment]
Hmm, definitely something fishy going on with your install.

I'm pretty sure we don't have a dependency on vue@ :)
I'm also pretty confident that there aren't any cyclic dependencies, since lerna checks for those.

I've just run a clean clone and install, and I get

$ du -sk
1216256	.

Looking at the paths you described above I see

4       ./algorithm/text/node_modules/@jsxcad
4       ./algorithm/text/node_modules/.bin
12      ./algorithm/text/node_modules
8       ./algorithm/text/dist
136     ./algorithm/text

Which is what I expect -- the dependencies in the sub-modules are hoisted back to the root.

I think probably your install didn't get symbolically linked properly.

Can you try a fresh install, then run the following?

npm install
npm run bootstrap
du -sk

If that doesn't work, then I guess we have an interesting problem. :)

**Comment by hrgdavor** [comment]
ok, thanks for looking into it. I tried the steps again.
- 524 MB - from git
- 633 MB - after npm install
- 1.12 GB - after npm run bootstrap

I should have done it before raising the issue. Thanks.

**Comment by pentacular** [comment]
No problem.

We need to put together better install instructions. :)

(Although we're not really ready for that quite yet)

**Comment by hrgdavor** [comment]
I am looking forward to seing your progress. I love coding in JS ans coding CAD for my 3d printing projects, so projects like yours are interesting to me.
I even started contributing to jscad for about a year now.
https://github.com/jscad/OpenJSCAD.org/discussions/944

I hope code-cad projects in JS will continue to grow, and even combine the ideas and tools.

**Comment by pentacular** [comment]
Sounds good.

If you're interested in trying it out, please let us know -- just be aware that it is quite volatile and not very polished. :)

**Comment by hrgdavor** [comment]
> If you're interested in trying it out, please let us know -- just be aware that it is quite volatile and not very polished. :)

I am interested, but swamped a bit right now. I put the repo on watch, but likely able to make time to try in few months from now. I do not mind it is not polished.

**Comment by hrgdavor** [comment]
that said. What is a simple way to try it a bit? 
are there some demos to try ?

**Comment by hrgdavor** [comment]
I do not see folder example/v1 mentioned on main readme in master branch
```
cd example/v1
npm run example square
```

**Comment by pentacular** [comment]
You could start with https://github.com/jsxcad/JSxCAD/blob/master/nb/start.md

There is a test server up on https://jsxcad.js.org/alpha/

That ought to link to an interactive and editable version of those notebooks but I see that our links didn't survive the switch from gitcdn.

I have a large change in progress, but I'll prioritize cleaning up the introductory experience after that.
