### ISSUE TITLE
Return of main() should handle arrays of objects to conform to the OpenJSCAD interface.

### ISSUE THREAD

**Issue by fischman** [jsxcad/JSxCAD#33]
OpenJSCAD encourages main() to return an array of objects instead of forcing a union() since that can be more efficient to render. IWBN for jsxcad's output methods to handle this as well.

(semantics should be the same as if the write method was handed the same array first passed through `union()`)

**Comment by pentacular** [comment]
writePaths and writeShape take multiple paths and shapes already, so I think this is covered at that level.

Note that returning an array of objects in OpenJSCAD isn't equivalent to returning a union of those objects -- abutting objects won't be merged, and overlapping objects will have interfering internal structure -- which is why it is more efficient.

And this is also true of writePaths and writeShape -- the objects passed through aren't merged.

Since the write methods aren't OpenJSCAD interfaces, I think the correct place to fix this in the code which receives the output of main(), which implements an OpenJSCAD interface.

Regarding the write methods, I think probably writeThreejs, writeStl, and writePdf should be retired, and replaced by adding support for a translation method, like 'pathsToPdf', etc. This should allow the data to be intercepted for display the browser, while maintaining the user's intent to, e.g., write a pdf, and allowing an actual pdf to be generated later for download.

If this makes sense, let's rename the issue to "Return of main() should handle arrays of objects to conform to the OpenJSCAD interface.".

What do you think?

**Comment by fischman** [comment]
Sorry, I was unaware of write{Paths,Shapes}; I was only ever talking about write{ThreejsPage,Stl,Pdf}

**Comment by pentacular** [comment]
Yeah -- * is dangerous like that. :)

I'll try to get writeStl and writePdf re-implemented in terms of writeShape / writePaths.

The need for the browser to be able to intercept the geometry for visualization while still needing to be able to download a rendered file weren't anticipated when I wrote out the initial implementation.

The 'main' interface also adds a bit of a challenge.

I guess that the right approach is probably to add an operator which produces a shape with an 'intent to express in a given format'.

Then you could say something like.

return [x.forPdf({}), y.forStl({})] and it would all work from the inside, while allowing UI or flags to override these intentions.

WDYT?

**Comment by pentacular** [comment]
I've fixed up writePdf and writeStl to accept multiple shapes, provide the geometries separately for rendering, and combine for file creation.

I haven't looked at the return of main yet.

**Comment by pentacular** [comment]
Having separated jscad loading out of the main api, this can be closed.
